### ISSUE TITLE
Duda sobre funcionamiento en ubuntu 22.04

### ISSUE THREAD

**Issue by LuisZambranaBlog** [jpxoi/send_whatsapp#1]
Hola jpxoi como estas? el desarrollo solo funciona con la la libreria importada o requiere tener instalado la aplicacion whatsapp? lo probe en ubuntu 22.04 lts y no hay caso. gracias por la idea y tu amable respuesta.

**Comment by jpxoi** [comment]
Hola @LuisZambranaBlog el módulo de pywhatkit requiere tener la versión de WhatsApp Web abierta en tu navegador con tu sesión ya iniciada. De tal forma, no hay forma de hacerlo funcionar exclusivamente desde consola, y requiere que tengas una versión de Ubuntu con Interfaz Gráfica y un navegador web.
